### ISSUE TITLE
No package.json

### ISSUE THREAD

**Issue by gaand** [ga-wdi-boston/ruby-vs-js-study#10]
So, you can't `npm install`

**Comment by BenGitsCode** [comment]
This should not have had an `npm install` instruction for cohort 015, but in accordance with issue #4 , more javascript will be added to the study in cohort 016, potentially closing this issue in the process.

**Comment by Jcornmanhomonoff** [comment]
There is now a package.json because the node template has been added....okay to close issue? @BenGitsCode @gaand

**Comment by BenGitsCode** [comment]
It hasn't been closed until the commit that addresses it is merged. You can edit your PR description to include `close #666` (with the real issue number) and it will close when the PR is merged to master OR the reviewer can add that to the merge commit created by the PR.

@gaand what's your preference when the keyword wasn't used in the PRs commits?

**Comment by jrhorn424** [comment]
@BenGitsCode @Jcornmanhomonoff I can answer that.

Drop a commit hash in, like this, then close the issue **but only if** you are not the PR originator.

Closeable as of 4bff030dc2e661c60c2897883baa664e704560c0.
